### ISSUE TITLE
[T3](2) Style checker

### ISSUE THREAD

**Issue by boraelci** [wu-rymd/kaiserschmarrn#6]
Set up style checker -> generate reports and add the results to repo

"Your entire codebase, including test cases and even trivial code, should be compliant with a style checker appropriate for your language/platform.  Include some reports from your style checker in your repository.  If it does not generate files, use redirection of output to a file, screenshots, or some other means to produce files."

**Comment by wu-rymd** [comment]
#12 Pull request
